services:
  postgres:
    image: postgres:latest
    container_name: md-postgres
    environment:
      POSTGRES_USER: johndoe
      POSTGRES_PASSWORD: somew0rds
      POSTGRES_DB: RentAGameDb
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgres/data
    networks:
      - md-network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: md-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: scoth@tiger.com
      PGADMIN_DEFAULT_PASSWORD: 123456
    ports:
      - "5051:80"
    depends_on:
      - postgres
    networks:
      - md-network

  rabbitmq:
    image: rabbitmq:management
    container_name: md-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: scothtiger
      RABBITMQ_DEFAULT_PASS: 123456
    ports:
      - "5673:5672"
      - "15673:15672"
    networks:
      - md-network

  redis:
    image: redis:latest
    container_name: md-redis
    ports:
      - "6380:6379"
    networks:
      - md-network
  
volumes:
  postgres_data:
  
networks:
  md-network:
    driver: bridge
